### ISSUE TITLE
Плеер

### ISSUE THREAD

**Issue by ARACOOOL** [ARACOOOL/tests#2]
Сделай точно таким же только убери все. Оставь полосу прокрутки кнопки по центру и вместо кнопок повтора и разброса поставь регулировку громкости . Остальное не нужно
![screenshot_2](https://cloud.githubusercontent.com/assets/539863/4517927/be21361c-4c64-11e4-9e94-3161405d7652.png)

**Comment by i80586** [comment]
тоже можно закрыть )
